export const GET_MODELS_LIST_REQUEST = 'models.GET_MODELS_LIST_REQUEST'
export const GET_MODELS_LIST_SUCCESS = 'models.GET_MODELS_LIST_SUCCESS'
export const GET_MODELS_LIST_ERROR = 'models.GET_MODELS_LIST_ERROR'

export const GET_MODEL_REQUEST = 'models.GET_MODEL_REQUEST'
export const GET_MODEL_SUCCESS = 'models.GET_MODEL_SUCCESS'
export const GET_MODEL_ERROR = 'models.GET_MODEL_ERROR'

export const TOOGLE_GLOBAL_LOADING = 'models.TOOGLE_GLOBAL_LOADING'
